Repository apple/swift-nio-transport-services, pull requests merged in 2022-06, with the labels that each got.

#148 change NIOTSNetworkEvent initializers visibility to public level
  Sources/NIOTransportServices/NIOTSNetworkEvents.swift
Labels: 🔼 needs-minor-version-bump

#149 Don't close when waiting unless we were asked to.
  Sources/NIOTransportServices/NIOTSConnectionChannel.swift
  Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
Labels: patch-version-bump-only

#150 Remove outdated docs from README
  README.md
Labels: needs-no-version-bump

#151 Use 5.7 nightlies.
  docker/docker-compose.2004.57.yaml
Labels: needs-no-version-bump
