Repository apple/swift-nio-transport-services, pull requests merged in 2025-04, with the labels that each got.

#229 Enable macOS CI on pull requests
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#228 Strict concurrency for NIOTransportServices and tests
  Package.swift
  Sources/NIOTransportServices/AcceptHandler.swift
  Sources/NIOTransportServices/Datagram/NIOTSDatagramBootstrap.swift
  Sources/NIOTransportServices/Datagram/NIOTSDatagramChannel.swift
  Sources/NIOTransportServices/Datagram/NIOTSDatagramListener.swift
  Sources/NIOTransportServices/Datagram/NIOTSDatagramListenerChannel.swift
  Sources/NIOTransportServices/NIOTSChannelOptions.swift
  Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
  Sources/NIOTransportServices/NIOTSConnectionChannel.swift
  Sources/NIOTransportServices/NIOTSEventLoop.swift
  Sources/NIOTransportServices/NIOTSEventLoopGroup.swift
  Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
  Sources/NIOTransportServices/NIOTSListenerChannel.swift
  Sources/NIOTransportServices/NIOTSNetworkEvents.swift
  Sources/NIOTransportServices/StateManagedListenerChannel.swift
  Sources/NIOTransportServices/StateManagedNWConnectionChannel.swift
  Tests/NIOTransportServicesTests/NIOFilterEmptyWritesHandlerTests.swift
  Tests/NIOTransportServicesTests/NIOTSAsyncBootstrapTests.swift
  Tests/NIOTransportServicesTests/NIOTSBootstrapTests.swift
  Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
  Tests/NIOTransportServicesTests/NIOTSDatagramConnectionChannelTests.swift
  Tests/NIOTransportServicesTests/NIOTSEndToEndTests.swift
  Tests/NIOTransportServicesTests/NIOTSEventLoopTests.swift
  Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
Labels: 🔨 semver/patch

#232 Enable Swift 6.1 jobs in CI
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#230 Add `NWParameters` configurator to bootstraps
  Sources/NIOTransportServices/Datagram/NIOTSDatagramBootstrap.swift
  Sources/NIOTransportServices/Datagram/NIOTSDatagramChannel.swift
  Sources/NIOTransportServices/Datagram/NIOTSDatagramListener.swift
  Sources/NIOTransportServices/Datagram/NIOTSDatagramListenerChannel.swift
  Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
  Sources/NIOTransportServices/NIOTSConnectionChannel.swift
  Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
  Sources/NIOTransportServices/NIOTSListenerChannel.swift
  Sources/NIOTransportServices/StateManagedListenerChannel.swift
  Sources/NIOTransportServices/StateManagedNWConnectionChannel.swift
  Tests/NIOTransportServicesTests/NIOTSBootstrapTests.swift
  Tests/NIOTransportServicesTests/NIOTSChannelMetadataTests.swift
  Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
  Tests/NIOTransportServicesTests/NIOTSDatagramConnectionChannelTests.swift
  Tests/NIOTransportServicesTests/NIOTSTestUtilities.swift
Labels: 🆕 semver/minor
